# Generated by Django 6.0.7 on 2026-07-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_description', models.TextField(help_text='Full JD text, used later for resume-JD matching')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_backlogs', models.PositiveIntegerField(blank=True, help_text='Maximum allowed active backlogs. Null = no limit.', null=True)),
                ('allowed_branches', models.JSONField(blank=True, default=list, help_text='List of allowed branch names, e.g. ["CSE", "ECE"]. Empty = all branches.')),
                ('min_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('max_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='drives.drive')),
            ],
        ),
    ]
