# Generated by Django 6.0.7 on 2026-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_drive_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
